### ISSUE TITLE
url: Secrets file not found: .kamal/secrets.

### ISSUE THREAD

**Issue by duleorlovic** [koenhandekyn/ops_backups#3]
The rails app is deployed using kamal
```
# config/deploy.yml
servers:
  web: *my-hosts

accessories:
  db:
    image: postgres:15.8
    host: *my-host

```

and for `pgdb console` there is an error
```
pgdb console
url: Secrets file not found: .kamal/secrets.
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "Secrets file not found: .kamal/secrets." does not exist
```

What is "environment" in `Environment here coresponds to the destination in Kamal.` ?

Also `pgdb console web` gives the same error
